[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this patch makes Byte work

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
local _size = math.max(1, self.ability.extra + (G.GAME.modifiers.booster_size_mod or 0))
'''
position = "after"
payload = '''
_size = _size + (G.GAME.extra_pack_size or 0)
'''
match_indent = true