[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this patch adds an cardarea used for (Jank) Flowey

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
consumeable_H = 0.95*G.CARD_H
'''
position = "after"
payload = '''
,
flowey_W = G.CARD_W * 3.1,
flowey_H = G.CARD_H
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.play = CardArea(
        0, 0,
        CAI.play_W,CAI.play_H, 
        {card_limit = 5, type = 'play'})
'''
position = "after"
payload = '''
self.flowey = CardArea(
        0, 0,
        CAI.offscreen_W,CAI.offscreen_H, 
        {card_limit = 3, type = 'joker'})
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.discard:hard_set_VT()
'''
position = "after"
payload = '''
G.flowey:hard_set_VT()
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.discard.T.x = G.jokers.T.x + G.jokers.T.w/2 + 0.3 + 15
        G.discard.T.y = 4.2

'''
position = "after"
payload = '''
G.flowey.T.x = G.jokers.T.x + G.jokers.T.w/2
G.flowey.T.y = G.jokers.T.y - 15

'''
match_indent = true