[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# this patch fixes lucky cards using a set value instead of a config valueable

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if SMODS.pseudorandom_probability(self, 'lucky_mult', 1, 5) then
'''
position = "at"
payload = '''
if SMODS.pseudorandom_probability(self, 'lucky_mult', 1, self.ability.extra.mult_chance) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if SMODS.pseudorandom_probability(self, 'lucky_money', 1, 15) then
'''
position = "at"
payload = '''
if SMODS.pseudorandom_probability(self, 'lucky_money', 1, self.ability.extra.money_chance) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
m_lucky =   {max = 500, order = 9, name = "Lucky Card", set = "Enhanced", pos = {x=4,y=1}, effect = "Lucky Card", label = "Lucky Card", config = {mult=20, p_dollars = 20}},
'''
position = "at"
payload = '''
m_lucky =   {max = 500, order = 9, name = "Lucky Card", set = "Enhanced", pos = {x=4,y=1}, effect = "Lucky Card", label = "Lucky Card", config = {mult = 20, p_dollars = 20, extra={mult_chance = 5, money_chance = 15}}},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
local numerator_mult, denominator_mult = SMODS.get_probability_vars(card, 1, 5, 'lucky_mult')
'''
position = "at"
payload = '''
local numerator_mult, denominator_mult = SMODS.get_probability_vars(card, 1, card.ability.extra.mult_chance, 'lucky_mult')
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
local numerator_dollars, denominator_dollars = SMODS.get_probability_vars(card, 1, 15, 'lucky_money')
'''
position = "at"
payload = '''
local numerator_dollars, denominator_dollars = SMODS.get_probability_vars(card, 1, card.ability.extra.money_chance, 'lucky_money')
'''
match_indent = true